[package]
name = "jmap-tools-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1.0"

[dependencies.jmap-tools]
path = ".."

[workspace]
members = ["."]

[[bin]]
name = "fuzz_json"
path = "fuzz_targets/fuzz_json.rs"
test = false
doc = false

[[bin]]
name = "fuzz_pointer"
path = "fuzz_targets/fuzz_pointer.rs"
test = false
doc = false
